### ISSUE TITLE
Top-level if doesn't work for structs

### ISSUE THREAD

**Issue by LennardF1989** [WerWolv/ImHex-Patterns#335] opened 2024-12-27 21:25 UTC
Consider:
```
    str extension = hex::prv::get_information("file_extension");
    
    if(extension == ".pel") {
        PEL pel @ 0x0;
    }
    else if(extension == ".ped") {
        PED ped @ 0x0;
    }
```

Won't show any output in the Pattern Data, while wrapping it into a struct will:

```
struct File {
    str extension = hex::prv::get_information("file_extension");
    
    if(extension == ".pel") {
        PEL pel;
    }
    else if(extension == ".ped") {
        PED ped;
    }
};

File file @ 0x0;
```

Version 1.36, installed with MSI.

**Comment by WerWolv** [comment] 2024-12-27 21:33
Duplicate of https://github.com/WerWolv/ImHex/issues/2018, I provided a more in-depth explanation as to why this is there.

**Closed by WerWolv** 2024-12-27 21:33 UTC
